[package]
name = "fast-pbf-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
osmpbf = "0.3.3"
osmpbfreader = "0.16.1"
rstar = "0.11.0"
scanf = "1.2.1"
